describe("Busted unit testing framework", function()
  describe("should handle profile utils", function()
    it("should return the default path for the profiles", function()
      assert.truthy(false)
    end)
  end)
end)
